//! Pure AI assistant domain types: chat messages, conversation threads, and
//! intent-based prompt construction.
//!
//! Nothing here touches the network or filesystem — every type and function is
//! fully testable in isolation and is exercised to 100 % coverage by the unit
//! tests at the bottom of this file.

/// The role of a message in a chat thread.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChatRole {
    /// A message from the human user.
    User,
    /// A message generated by the AI assistant.
    Assistant,
    /// An invisible system instruction that precedes the conversation.
    System,
}

impl ChatRole {
    /// The canonical lowercase string key for this role.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Assistant => "assistant",
            Self::System => "system",
        }
    }

    /// Parse a lowercase string into a `ChatRole`, returning `None` for
    /// unrecognised values.
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "user" => Some(Self::User),
            "assistant" => Some(Self::Assistant),
            "system" => Some(Self::System),
            _ => None,
        }
    }
}

/// A single message in a chat conversation.
#[derive(Debug, Clone, PartialEq)]
pub struct ChatMessage {
    /// Who sent this message.
    pub role: ChatRole,
    /// The text of the message.
    pub content: String,
}

impl ChatMessage {
    /// Create a user message with the given content.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: ChatRole::User,
            content: content.into(),
        }
    }

    /// Create an assistant message with the given content.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: ChatRole::Assistant,
            content: content.into(),
        }
    }

    /// Create a system message with the given content.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: ChatRole::System,
            content: content.into(),
        }
    }
}

/// An in-memory conversation thread — an ordered list of messages.
#[derive(Debug, Default)]
pub struct ChatThread {
    messages: Vec<ChatMessage>,
}

impl ChatThread {
    /// Create an empty thread.
    pub fn new() -> Self {
        Self {
            messages: Vec::new(),
        }
    }

    /// Append a message to the end of the thread.
    pub fn push(&mut self, msg: ChatMessage) {
        self.messages.push(msg);
    }

    /// Read-only view of all messages.
    pub fn messages(&self) -> &[ChatMessage] {
        &self.messages
    }

    /// Truncate the thread to at most `max` messages, dropping the oldest.
    /// A no-op when `messages.len() <= max`.
    pub fn trim_to(&mut self, max: usize) {
        if self.messages.len() > max {
            self.messages.drain(..self.messages.len() - max);
        }
    }

    /// Number of messages in the thread.
    pub fn len(&self) -> usize {
        self.messages.len()
    }

    /// Returns `true` when the thread contains no messages.
    pub fn is_empty(&self) -> bool {
        self.messages.is_empty()
    }
}

/// The intent behind a chat interaction — drives how the prompt is assembled.
#[derive(Debug, Clone, PartialEq)]
pub enum ChatIntent {
    /// Explain the selected LaTeX text in its surrounding context.
    Explain {
        /// The highlighted LaTeX text.
        selection: String,
        /// Surrounding document text (may be empty when no context is available).
        context: String,
    },
    /// Propose a minimal fix for a compile error.
    FixError {
        /// The full compile log.
        error_log: String,
        /// The failing snippet extracted from the source.
        snippet: String,
    },
    /// Rewrite / transform the selected LaTeX text.
    Transform {
        /// The LaTeX text to rewrite.
        selection: String,
    },
}

/// Assemble the `(role, content)` pairs to send to the LLM for the given
/// intent and conversation history.
///
/// The system message is always first; prior `history` messages follow
/// (in order); the new user message is appended last.
pub fn build_chat_prompt(intent: &ChatIntent, history: &[ChatMessage]) -> Vec<(String, String)> {
    let system = match intent {
        ChatIntent::Explain { .. } => {
            "You are a helpful LaTeX expert. Explain the provided LaTeX concisely \
             and clearly. Do not propose edits unless explicitly asked."
        }
        ChatIntent::FixError { .. } => {
            "You are a LaTeX compile-error fixer. Analyse the error log and the \
             failing snippet, then provide a corrected version inside a fenced \
             ```latex code block. Keep changes minimal."
        }
        ChatIntent::Transform { .. } => {
            "You are a LaTeX editor. Rewrite the provided LaTeX as instructed. \
             Return the replacement inside a fenced ```latex code block."
        }
    };

    let user_message = match intent {
        ChatIntent::Explain { selection, context } => {
            if context.is_empty() {
                format!("Explain this LaTeX:\n\n```latex\n{selection}\n```")
            } else {
                format!(
                    "Explain this LaTeX in context:\n\n```latex\n{selection}\n```\n\n\
                     Surrounding document:\n```latex\n{context}\n```"
                )
            }
        }
        ChatIntent::FixError { error_log, snippet } => {
            format!(
                "Fix the compile error.\n\nError log:\n```\n{error_log}\n```\n\n\
                 Failing snippet:\n```latex\n{snippet}\n```"
            )
        }
        ChatIntent::Transform { selection } => {
            format!("Rewrite this LaTeX:\n\n```latex\n{selection}\n```")
        }
    };

    let mut out: Vec<(String, String)> = Vec::new();
    out.push(("system".into(), system.into()));
    for msg in history {
        out.push((msg.role.as_str().into(), msg.content.clone()));
    }
    out.push(("user".into(), user_message));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── ChatRole ──────────────────────────────────────────────────────────────

    #[test]
    fn chat_role_as_str_round_trips() {
        for role in [ChatRole::User, ChatRole::Assistant, ChatRole::System] {
            let s = role.as_str();
            assert_eq!(ChatRole::parse(s), Some(role));
        }
    }

    #[test]
    fn chat_role_parse_unknown_returns_none() {
        assert_eq!(ChatRole::parse("unknown"), None);
        assert_eq!(ChatRole::parse(""), None);
        assert_eq!(ChatRole::parse("USER"), None);
    }

    #[test]
    fn chat_role_debug_eq_copy() {
        let a = ChatRole::User;
        let b = a;
        assert_eq!(a, b);
        assert_ne!(a, ChatRole::Assistant);
        assert_ne!(a, ChatRole::System);
        assert!(format!("{a:?}").contains("User"));
    }

    // ── ChatMessage ───────────────────────────────────────────────────────────

    #[test]
    fn chat_message_constructors_set_role_and_content() {
        let u = ChatMessage::user("hello");
        assert_eq!(u.role, ChatRole::User);
        assert_eq!(u.content, "hello");

        let a = ChatMessage::assistant("hi");
        assert_eq!(a.role, ChatRole::Assistant);
        assert_eq!(a.content, "hi");

        let s = ChatMessage::system("be terse");
        assert_eq!(s.role, ChatRole::System);
        assert_eq!(s.content, "be terse");
    }

    #[test]
    fn chat_message_eq_clone_debug() {
        let a = ChatMessage::user("ping");
        let b = a.clone();
        assert_eq!(a, b);
        assert_ne!(a, ChatMessage::assistant("ping"));
        assert!(format!("{a:?}").contains("ChatMessage"));
    }

    // ── ChatThread ────────────────────────────────────────────────────────────

    #[test]
    fn chat_thread_starts_empty() {
        let t = ChatThread::new();
        assert!(t.is_empty());
        assert_eq!(t.len(), 0);
        assert_eq!(t.messages(), &[]);
    }

    #[test]
    fn chat_thread_default_is_empty() {
        let t = ChatThread::default();
        assert!(t.is_empty());
    }

    #[test]
    fn chat_thread_push_and_len() {
        let mut t = ChatThread::new();
        t.push(ChatMessage::user("a"));
        t.push(ChatMessage::assistant("b"));
        assert_eq!(t.len(), 2);
        assert!(!t.is_empty());
        assert_eq!(t.messages()[0].content, "a");
        assert_eq!(t.messages()[1].content, "b");
    }

    #[test]
    fn chat_thread_trim_to_drops_oldest() {
        let mut t = ChatThread::new();
        for i in 0..5 {
            t.push(ChatMessage::user(i.to_string()));
        }
        t.trim_to(3);
        assert_eq!(t.len(), 3);
        assert_eq!(t.messages()[0].content, "2");
        assert_eq!(t.messages()[2].content, "4");
    }

    #[test]
    fn chat_thread_trim_to_is_noop_when_at_or_below_max() {
        let mut t = ChatThread::new();
        t.push(ChatMessage::user("a"));
        t.push(ChatMessage::user("b"));
        t.trim_to(2);
        assert_eq!(t.len(), 2);
        t.trim_to(5);
        assert_eq!(t.len(), 2);
    }

    #[test]
    fn chat_thread_debug() {
        assert!(format!("{:?}", ChatThread::new()).contains("ChatThread"));
    }

    // ── ChatIntent ────────────────────────────────────────────────────────────

    #[test]
    fn chat_intent_explain_stores_fields() {
        let i = ChatIntent::Explain {
            selection: "x".into(),
            context: "y".into(),
        };
        assert_eq!(
            i,
            ChatIntent::Explain {
                selection: "x".into(),
                context: "y".into()
            }
        );
        assert!(format!("{i:?}").contains("Explain"));
        let _ = i.clone();
    }

    #[test]
    fn chat_intent_fix_error_stores_fields() {
        let i = ChatIntent::FixError {
            error_log: "err".into(),
            snippet: "code".into(),
        };
        assert_eq!(
            i,
            ChatIntent::FixError {
                error_log: "err".into(),
                snippet: "code".into()
            }
        );
        assert!(format!("{i:?}").contains("FixError"));
    }

    #[test]
    fn chat_intent_transform_stores_field() {
        let i = ChatIntent::Transform {
            selection: "s".into(),
        };
        assert_eq!(
            i,
            ChatIntent::Transform {
                selection: "s".into()
            }
        );
        assert!(format!("{i:?}").contains("Transform"));
    }

    // ── build_chat_prompt ─────────────────────────────────────────────────────

    #[test]
    fn explain_prompt_without_context_starts_with_system_and_ends_with_user() {
        let intent = ChatIntent::Explain {
            selection: "\\textbf{hello}".into(),
            context: "".into(),
        };
        let pairs = build_chat_prompt(&intent, &[]);
        assert_eq!(pairs.len(), 2);
        assert_eq!(pairs[0].0, "system");
        assert!(pairs[0].1.contains("LaTeX expert"));
        assert_eq!(pairs[1].0, "user");
        assert!(pairs[1].1.contains("\\textbf{hello}"));
        assert!(!pairs[1].1.contains("Surrounding"));
    }

    #[test]
    fn explain_prompt_with_context_includes_surrounding_block() {
        let intent = ChatIntent::Explain {
            selection: "\\emph{x}".into(),
            context: "\\begin{document}".into(),
        };
        let pairs = build_chat_prompt(&intent, &[]);
        let user = &pairs[pairs.len() - 1].1;
        assert!(user.contains("Surrounding"));
        assert!(user.contains("\\begin{document}"));
    }

    #[test]
    fn fix_error_prompt_contains_error_log_and_snippet() {
        let intent = ChatIntent::FixError {
            error_log: "! Undefined control sequence.".into(),
            snippet: "\\unknowncmd".into(),
        };
        let pairs = build_chat_prompt(&intent, &[]);
        assert_eq!(pairs[0].0, "system");
        assert!(pairs[0].1.contains("error fixer"));
        let user = &pairs[pairs.len() - 1].1;
        assert!(user.contains("Undefined control sequence"));
        assert!(user.contains("\\unknowncmd"));
    }

    #[test]
    fn transform_prompt_contains_selection() {
        let intent = ChatIntent::Transform {
            selection: "\\section{Old}".into(),
        };
        let pairs = build_chat_prompt(&intent, &[]);
        assert!(pairs[0].1.contains("editor"));
        let user = &pairs[pairs.len() - 1].1;
        assert!(user.contains("\\section{Old}"));
        assert!(user.contains("Rewrite"));
    }

    #[test]
    fn prompt_includes_history_messages_between_system_and_user() {
        let history = vec![
            ChatMessage::user("first question"),
            ChatMessage::assistant("first answer"),
        ];
        let intent = ChatIntent::Transform {
            selection: "x".into(),
        };
        let pairs = build_chat_prompt(&intent, &history);
        assert_eq!(pairs.len(), 4);
        assert_eq!(pairs[0].0, "system");
        assert_eq!(pairs[1], ("user".into(), "first question".into()));
        assert_eq!(pairs[2], ("assistant".into(), "first answer".into()));
        assert_eq!(pairs[3].0, "user");
    }

    #[test]
    fn prompt_with_empty_history_has_only_system_and_user() {
        let intent = ChatIntent::FixError {
            error_log: "e".into(),
            snippet: "s".into(),
        };
        let pairs = build_chat_prompt(&intent, &[]);
        assert_eq!(pairs.len(), 2);
        assert_eq!(pairs[0].0, "system");
        assert_eq!(pairs[1].0, "user");
    }
}
