import { test, expect, type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';

// Regenerates the marketing screenshots into docs/assets/. Run with
// `just screenshots`. The web build has no TeX engine, so its in-memory compile
// returns a real pre-rendered proof of the sample below (see
// apps/desktop/src/lib/sample-proof.ts) — the editor and the live PDF.js preview
// are both genuine, so the shots show an honest editor-and-proof view.
const OUT = '../../docs/assets';
mkdirSync(OUT, { recursive: true });

/** Seed localStorage before the app boots (theme, onboarding state). */
async function seed(page: Page, theme: string, onboarded = true): Promise<void> {
  await page.addInitScript(
    ([t, o]) => {
      window.localStorage.setItem('galley:theme', t as string);
      if (o) {
        window.localStorage.setItem('galley:onboarded', 'true');
      } else {
        window.localStorage.removeItem('galley:onboarded');
      }
    },
    [theme, onboarded]
  );
}

/**
 * The sample source. It is the very document the embedded proof was typeset from
 * (regenerated by the `writes_the_sample_proof` helper in
 * crates/galley-compile/tests/real_compile.rs), so the editor on the left and the
 * proof on the right are the same document.
 */
const SAMPLE = `\\documentclass{article}
\\title{Pull a Proof}
\\author{Galley}
\\date{}
\\begin{document}
\\maketitle
\\section{Introduction}\\label{sec:intro}
Galley sets your source in type and pulls a live proof. The mass--energy
relation,
\\begin{equation}
  E = mc^2,
\\end{equation}
follows from the postulates of special relativity. See Section~\\ref{sec:intro}.
\\section{Method}
Edit on the left; the proof on the right refreshes as you type.
\\end{document}`;

/** Open the demo project, set the sample source, and compile a live proof. */
async function openWithProof(page: Page): Promise<void> {
  await page.goto('/');
  await page
    .getByRole('region', { name: 'Project dashboard' })
    .getByRole('button', { name: 'Open a folder…' })
    .click();
  const editor = page.getByLabel('LaTeX source');
  await expect(editor).toBeVisible();
  await editor.click();
  await page.keyboard.press('ControlOrMeta+a');
  await page.keyboard.insertText(SAMPLE);
  await page.keyboard.press('ControlOrMeta+Home'); // show the document top
  await page.getByRole('button', { name: 'Compile' }).click();
  // Wait for the proof canvas, then let PDF.js paint the page before the shot.
  await expect(page.getByLabel('Proof')).toBeVisible();
  await expect(page.getByText('1 / 1')).toBeVisible();
  await page.waitForTimeout(400);
}

test('dashboard launcher', async ({ page }) => {
  await seed(page, 'onionskin');
  await page.goto('/');
  await expect(page.getByRole('region', { name: 'Project dashboard' })).toBeVisible();
  await page.screenshot({ path: `${OUT}/dashboard.png` });
});

test('first-run onboarding tour', async ({ page }) => {
  await seed(page, 'onionskin', false);
  await page.goto('/');
  await expect(page.getByRole('dialog', { name: 'Welcome to Galley' })).toBeVisible();
  await page.screenshot({ path: `${OUT}/onboarding.png` });
});

test('editor and proof — Onionskin (hero)', async ({ page }) => {
  await seed(page, 'onionskin');
  await openWithProof(page);
  await page.screenshot({ path: `${OUT}/editor-onionskin.png` });
});

test('editor and proof — Carbon', async ({ page }) => {
  await seed(page, 'carbon');
  await openWithProof(page);
  await page.screenshot({ path: `${OUT}/editor-carbon.png` });
});

test('editor and proof — Carbon High-Contrast', async ({ page }) => {
  await seed(page, 'carbon-hc');
  await openWithProof(page);
  await page.screenshot({ path: `${OUT}/editor-carbon-hc.png` });
});

test('settings — appearance', async ({ page }) => {
  await seed(page, 'onionskin');
  await openWithProof(page);
  await page.getByRole('button', { name: 'Settings' }).click();
  await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible();
  await page.screenshot({ path: `${OUT}/settings.png` });
});
